version: "3"
services:
  app:
    container_name: bako-abah-node-v1
    restart: on-failure
    build: .
    depends_on:
      - db
    links:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/dev-bako-srv
      NODE_ENV: development
    ports:
      - "8080:8080"
    command: npm start  
    volumes:
      - .:/app/
      - /app/node_modules
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev-bako-srv
      
